---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common

  - ../../../functions/compute/c01
  - ../../../functions/network/n04
  - ../../../functions/storage/s02

  - ../../keystone_ldap
