apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cabpk-system

namePrefix: cpbpk-

commonLabels:
  control-plane: cabpk-controller-manager

resources:
  - ./namespace.yaml
  - ./crd
  - ./certmanager
  - ./manager
  - ./rbac
  - ./webhook
