apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capi-system

namePrefix: capi-

commonLabels:
  control-plane: cluster-api-controller-manager

resources:
  - ./namespace.yaml
  - ./crd
  - ./certmanager
  - ./manager
  - ./rbac
  - ./webhook
